-- MySQL Script generated by MySQL Workbench
-- Thu Feb  2 12:15:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tadalafit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tadalafit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tadalafit` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tadalafit` ;

-- -----------------------------------------------------
-- Table `tadalafit`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tadalafit`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
INSERT INTO administrador (nome,user, password,cpf) VALUES ("admin", "admin","123","000.000.00-00");


-- -----------------------------------------------------
-- Table `tadalafit`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tadalafit`.`aluno` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `data_nascimento` VARCHAR(10) NULL DEFAULT NULL,
  `altura` DOUBLE NULL DEFAULT NULL,
  `peso` DOUBLE NULL DEFAULT NULL,
  `bf` DOUBLE NULL DEFAULT NULL,
  `comorbidade` VARCHAR(45) NULL DEFAULT NULL,
  `matricula_prof_encarregado` INT NULL DEFAULT NULL,
  `treino_a` JSON NULL DEFAULT NULL,
  `treino_b` JSON NULL DEFAULT NULL,
  `treino_c` JSON NULL DEFAULT NULL,
  `treino_d` JSON NULL DEFAULT NULL,
  `treino_e` JSON NULL DEFAULT NULL,
  `situacao` VARCHAR(45) NULL DEFAULT 'ATIVO',
  `dt_pagamento` varchar(35) DEFAULT (date_format(curdate(),_utf8mb4'%d/%m/%Y %H:%i:%S')),
  `foto` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
INSERT INTO aluno (matricula,usuario,senha,nome,sexo,cpf,telefone,email,data_nascimento,altura,peso, bf,comorbidade,matricula_prof_encarregado, treino_a,treino_b,treino_c,treino_d,treino_e,situacao, dt_pagamento,foto)
 VALUES (1,'clara','ana','ana clara','fem','1111111','11111111','aaaaaaaa@gmail.com','21/08/2001',1.85,75.2,12,'Nenhuma',1,'{\"rosca_scott\": [\"4x8\"], \"rosca_direta\": [\"3x12\", \"excentrico\"]}','{\"supino\": [\"3x12\"], \"triceps\": [\"4x8\"]}','{\"perna\": [\"3x12\"], \"panturra\": [\"4x8\"]}',NULL,NULL,'pago','27/01/2023 00:00:00',NULL);


-- -----------------------------------------------------
-- Table `tadalafit`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tadalafit`.`professor` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cref` VARCHAR(45) NOT NULL,
  `foto` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `idprofessor_UNIQUE` (`matricula` ASC) VISIBLE,
  UNIQUE INDEX `cref_UNIQUE` (`cref` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
INSERT INTO professor (matricula,usuario,senha,nome,telefone,email,cref,foto) VALUES (1,"professor","123","professor","00000-0000","professor@gmail.com","000000-P");


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
